# raagafellas.py

raagafellas = [

#==========================================================
#----------------------------------------------------------
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# 2009 admits (Conal)
	{'name': 'Dustin Janatpour',
	'part':['bass', 'vp'],
	'start': 2009,
	'end': 2011,
	'program':'undergrad',
	'study': 'Mcs',
	'officer': ['MD'],
	'arranged':['HEK'],
	'training': 'choir',
	'ethnicity': 'white/persian',
	'sub-ethnicity':'white/persian',
	'solos': ['Vande yahan vahan'],
	'notes': "When village is lead by duck, it is sort of probably most likely a very bad thing"
	},		
	{'name': 'Arun Miduthuri',
	'part':['bari'],
	'start': 2009,
	'end': 2011,
	'program':'master',
	'study': 'EE',
	'officer': ['pres'],
	'arranged':[],
	'training': 'hindustani',
	'ethnicity': 'south asian',
	'sub-ethnicity':'telugu',
	'solos': ['Chan Chan (swaram)', 'Hallelujah (3)', 'Humdum', 'Oru Maalai', 'Vande tere pas'],
	},		
	{'name': 'Aditya Anchuri',
	'part':['lead'],
	'start': 2009,
	'end': 2011,
	'program':'master',
	'study': 'EE',
	'officer': [],
	'arranged':[],
	'training': 'pop (post?)',
	'ethnicity': 'south asian',
	'sub-ethnicity':'telugu',
	'solos': ['Kangna', 'Oru Maalai (Paathupazhakiya)', 'Vande high aalap'],
	},	
	{'name': 'Anirudh Venkatesh',
	'part':['bari', 'vp'],
	'start': 2009,
	'end': 2011,
	'program':'undergrad',
	'study': 'cs',
	'officer': ['AssMD'],
	'arranged':[],
	'training': 'carnatic',
	'ethnicity': 'south asian',
	'sub-ethnicity':'tamil',
	'solos': ['Chan Chan', 'Jaane Kya Chahe','Kangna', 'Vande Aalap', 'Woh Lamhe'],
	},
	{'name': 'Sashendra Aponso',
	'part':['top', 'lead'],
	'start': 2007,
	'end': 2011,
	'program':'undergrad',
	'study': 'humbio',
	'officer': [],
	'arranged':['Surangana Kiriliye'],
	'training': 'hindustani',
	'ethnicity': 'south asian',
	'sub-ethnicity':'sinhalese',
	'solos': ["I'll take you home", 'Oru Maalai (?)'],
	'notes': 'first student admitted to Stanford from Oman; published author.  did Raag his freshman and senior year'
	},		
	{'name': 'RJ Lim',
	'part':['bari', 'bass'],
	'start': 2009,
	'end': 2013, #A little uncertain here
	'program':'undergrad',
	'study': 'cs',
	'officer': [],
	'arranged':[],
	'training': '?',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': ['humdum', 'Oka Maaru'],
	},		
#==========================================================
#----------------------------------------------------------
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# 2010 admits (Dustin)
	{'name': 'Isaac Caswell',
	'part':['top', 'bass'],
	'start': 2010,
	'end': 2015,
	'program':'undergrad',
	'study': 'symsys',
	'officer': ['MD', 'pres'],
	'arranged':['Bure Bure', 'Aicha', 'Swing Low/Mangalyam', 'Chandrachooda'],
	'training': 'none',
	'ethnicity': 'white',
	'sub-ethnicity':'white',
	'sub-sub-ethnicity':'irish/english/german',
	'solos': ['Aicha (French)', 'Aicha (Arabic)', 'Chaiyyan Chaiyyan (Yaar Masale)', 'Hallelujah (harmony)', 'Ey Karevan (harmony)', 'Ey Karevan', 'Oka Maaru', 'paathupazhakiya', 'Swing Low (upper)', 'Vande high aalap', 'Vande yahan vahan', 'Vande yahan vahan (harmony)'],
	'father': 'Conal Sathi',
	},

	{'name': 'Raman Nelakanti',
	'part':['bari', 'bass'],
	'start': 2010,
	'end': 2013.5,
	'program':'undergrad',
	'study': 'bioe',
	'officer': ['MD'],
	'arranged':['?', 'Chaiyyan Chaiyyan', 'Roobaroo/Payphone'],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'telugu',
	'solos': ['Chandrachooda (bass sargam)', 'Chaiyyan Chaiyyan', 'Jaane Kya Chahe', 'Motel (???)', "Humdum", "Vande Aalap"],
	},

	{'name': 'Arif Gilani',
	'part':['bari'],
	'start': 2010,
	'end': 2012,
	'program':'undergrad',
	'study': 'humbio',
	'officer': ['pres'],
	'arranged':[],
	'training': 'mosque',
	'ethnicity': 'south asian',
	'sub-ethnicity':'pakistani',
	'solos': ['Jaane Kya Chahe', 'Oka Maaru', 'Vande tere pas'],
	},		

	{'name': 'Praveen Ramesh',
	'part':['lead'],
	'start': 2010,
	'end': 2012,
	'program':'undergrad',
	'study': 'humbio',
	'officer': [],
	'arranged':[],
	'training': 'musical theater',
	'ethnicity': 'south asian',
	'sub-ethnicity':'tamil',
	'solos': ['Burn', 'Chaiyyan Chaiyyan (Yaar Masale on)', 'Hallelujah (1+2)', 'Kangna', 'Oru Maalai'],
	},	
	{'name': 'Jason Kaufman',
	'part':['top'],
	'start': 2010,
	'end': 2011,
	'program':'undergrad',
	'study': '??',
	'officer': [],
	'arranged':[],
	'training': 'none?',
	'ethnicity': 'white',
	'sub-ethnicity':'jewish',
	'solos': [],
	},		
	{'name': 'Michael Chen',
	'part':['top'],
	'start': 2010,
	'end': 2011,
	'program':'undergrad',
	'study': '??',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'taiwanese',
	'solos': [],
	},		
	{'name': 'Kevin Guo',
	'part':['bass', 'vp'],
	'start': 2010,
	'end': 2010.6,
	'program':'undergrad',
	'study': '??',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': ['Vande yahan vahan',],
	},		
#==========================================================
#----------------------------------------------------------
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# 2011 admits (Raman)
	
	{'name': 'Vivek Choksi',
	'part':['top'],
	'start': 2011,
	'end': 2013,
	'program':'undergrad',
	'study': 'cs',
	'officer': ['MD'],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'gujarati',
	'solos': ['Burn', 'Ab Laut Aa', 'Chak De', 'Chan Chan', 'Hallelujah (3)', "Oru Maalai (?)"],
	},		
	{'name': 'Bryan Li',
	'part':['bass'],
	'start': 2011,
	'end': 2013,
	'program':'undergrad',
	'study': '?',
	'officer': ['pres'],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': ['Motel', 'Humdum (dheem dheem)','Vande yahan vahan'],
	},		
	{'name': 'Amrit Saxena',
	'part':['bari'],
	'start': 2011,
	'end': 2013,
	'program':'undergrad',
	'study': 'cs',
	'officer': ['pres'],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'?',
	'solos': ['Motel'],
	},

	{'name': 'Ian HoIms',
	'part':['bass'],
	'start': 2011,
	'end': 2013,
	'program':'undergrad',
	'study': 'cs?',
	'officer': ['MD'],
	'arranged':[],
	'training': 'none?',
	'ethnicity': 'white',
	'sub-ethnicity':'white',
	'solos': ['Motel'],
	},
	{'name': 'Justin Cavazos',
	'part':['top'],
	'start': 2011,
	'end': 2013,
	'program':'undergrad',
	'study': 'Music',
	'officer': [],
	'arranged':['Obsessed with You'],
	'training': 'choir',
	'ethnicity': 'hispanic',
	'sub-ethnicity':'mexican',
	'solos': ['This Love', 'Obsessed with You', 'Hallelujah (3)', "Motel (it's all right)"],
	},	
	{'name': 'Linyi Gao',
	'part':['lead'],
	'start': 2011,
	'end': 2012,
	'program':'undergrad',
	'study': 'Physics',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': [],
	},		
	{'name': 'Andrew Guo',
	'part':['lead'],
	'start': 2011,
	'end': 2012,
	'program':'undergrad',
	'study': 'physics',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': [],
	},				
	{'name': 'Mahesh Agarwal',
	'part':['bari'],
	'start': 2011,
	'end': 2012,
	'program':'undergrad',
	'study': 'cs',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'?',
	'solos': ['Vande yahan vahan'],
	},
	{'name': 'John Shih',
	'part':['bass', 'vp'],
	'start': 2011,
	'end': 2012,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': [],
	},	
#==========================================================
#----------------------------------------------------------
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
#2012 admitees, under Vivek
	{'name': 'Akshay Subramaniam',
	'part':['bari'],
	'start': 2012,
	'end': 2014,
	'program':'PhD',
	'study': 'astro/aero',
	'officer': ['MD'],
	'arranged':['PDS'],
	'training': 'carnatic, hindustani',
	'ethnicity': 'south asian',
	'sub-ethnicity':'telugu',
	'solos': ['Jaane Kya Chahe','Burn', 'Aicha (Urdu)', 'Ajab Si', 'Chandrachooda', 'Mahabharat', "Motel (it's all right)", 'Oru Maalai', 'Pani Da', 'Roobaroo', 'Vande tere pas'],
	},

	{'name': 'Lowry Yankwich',
	'part':['lead'],
	'start': 2012,
	'end': 2014,
	'program':'undergrad',
	'study': '?',
	'officer': ['ASS MD'],
	'arranged':['PDS'],
	'training': 'choir?',
	'ethnicity': 'white',
	'sub-ethnicity':'white',
	'solos': ['Burn', 'Hallelujah (1+2)', 'Hallelujah (harmony)', 'Payphone', 'Tum Hi Ho', 'Swing Low (lower)', 'Vande high aalap'],
	},
	{'name': 'Akaash Nanda',
	'part':['bari'],
	'start': 2012,
	'end': 2013.333,
	'program':'undergrad',
	'study': 'symsys',
	'officer': ['pres'],
	'arranged':[],
	'training': 'hindustani',
	'ethnicity': 'south asian',
	'sub-ethnicity':'oriya',
	'solos': ['Aicha (Urdu)', 'Chaiyyan Chaiyyan', "Motel (it's all right)"],
	},
	{'name': 'David Jiang',
	'part':['bass'],
	'start': 2012,
	'end': 2016,
	'program':'undergrad',
	'study': 'cs',
	'officer': ['pres'],
	'arranged':[],
	'training': 'none?',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': ['Payphone', 'I dreamed a dream'],
	},
	{'name': 'Junxu Li',
	'part':['lead'],
	'start': 2011,
	'end': 2012,
	'program':'grad?',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'sub-sub-ethnicity':'singaporean chinese',	
	'solos': ['Hallelujah (harmony)'],
	},
	{'name': 'Kunal Sangani',
	'part':['bari'],
	'start': 2012,
	'end': 2013.1,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'western classical',
	'ethnicity': 'south asian',
	'sub-ethnicity':'gujarati?',
	'solos': ['Hallelujah (1+2)'],
	},		
	{'name': 'Aditya Kanukurthy',
	'part':['lead'],
	'start': 2012,
	'end': 2013,
	'program':'undergrad',
	'study': 'econ',
	'officer': [],
	'arranged':[],
	'training': 'carnatic',
	'ethnicity': 'south asian',
	'sub-ethnicity':'marathi/tamil',
	'solos': ['Bure Bure', 'Kangna'],
	},
	{'name': 'Daniel Maren',
	'part':['top', 'vp'],
	'start': 2012,
	'end': 2013,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'indonesian/white/south asian',
	'sub-ethnicity':'indonesian/white/tamil',
	'solos': [],
	},
	{'name': 'Miguel Francisco',
	'part':['top'],
	'start': 2012,
	'end': 2013,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'sub-sub-ethnicity':'chinese filipino',
	'solos': ['Meri Jaan'],
	},
	{'name': 'Sendil Palani',
	'part':['top'],
	'start': 2012,
	'end': 2012.02,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'tamil',
	'solos': [],
	},

#==========================================================
#----------------------------------------------------------
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
#2012 admitees, under Akshay/Lowry	
	{'name': 'Kartik Sawhney',
	'part':['lead'],
	'start': 2013,
	'end': 2015,
	'program':'undergrad',
	'study': 'cs',
	'officer': ['pres'],
	'arranged':[],
	'training': 'hindustani',
	'ethnicity': 'south asian',
	'sub-ethnicity':'punjabi',
	'solos': ['Jaane Kya Chahe','Chan Chan (Koh Yaal)', 'Chandrachooda', 'Kangna', 'Mahabharat', 'Vande Aalap'],
	},	
	{'name': 'Manaswi Mishra',
	'part':['bari'],
	'start': 2013,
	'end': 2014.01,
	'program':'master',
	'study': 'CCRMA',
	'officer': [],
	'arranged':[],
	'training': 'informal',
	'ethnicity': 'south asian',
	'sub-ethnicity':'oriya',
	'solos': ['Chandrachooda (konnakol)', 'Hallelujah (3)', 'Oka Maaru', 'Superstition'],
	},
	{'name': 'Ye Wang',
	'part':['bass', 'vp'],
	'start': 2013,
	'end': 2015,
	'program':'undergrad',
	'study': 'cs',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': [],
	},	
	{'name': 'Edward Wang',
	'part':['bass'],
	'start': 2013,
	'end': 2014,
	'program':'undergrad',
	'study': 'cs',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': [],
	},
	{'name': 'Bradley Wo',
	'part':['lead'],
	'start': 2013,
	'end': 2014,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': [],
	'solos':['Ab Laut Aa', 'Aicha (Arabic)'],
	},	
	{'name': 'Nathan Randall',
	'part':['bass'],
	'start': 2013,
	'end': 2013.85,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'choir',
	'ethnicity': 'white',
	'sub-ethnicity':'white/lebanese',
	'solos': ['Chan Chan', 'Swing Low (If you get there...)'],
	},

	{'name': 'Jordan Brzezny',
	'part':['top'],
	'start': 2013,
	'end': 2013.6,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'white',
	'sub-ethnicity':'white',
	'solos': [],
	},
	{'name': 'Karan Mathur',
	'part':['top'],
	'start': 2013,
	'end': 2014,
	'program':'undergrad',
	'study': 'symsys?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'punjabi?',
	'solos': [],
	},
	{'name': 'Milan Doshi',
	'part':['bari'],
	'start': 2013,
	'end': 2014,
	'program':'undergrad',
	'study': 'cs?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'gujarati',
	'solos': ['Chaiyyan Chaiyyan (main uski...)', 'Roobaroo'],
	},
	{'name': 'Diveesh Singh',
	'part':['top'],
	'start': 2013,
	'end': 2013.1,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'punjabi',
	'solos': [],
	},
#==========================================================
#----------------------------------------------------------
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
#2014 admitees, under Isaac	
	{'name': 'Onkur Sen',
	'part':['top'],
	'start': 2014,
	'end': 2016,
	'program':'master',
	'study': 'cs',
	'officer': ['MD'],
	'arranged':[],
	'training': 'informal',
	'ethnicity': 'south asian',
	'sub-ethnicity':'bengali',
	'solos': ['Burn', 'Chandrachooda (konnakol)', 'Chaiyyan, Chaiyyan', "Motel", 'Oru Maalai','Vande high aalap' ],
	},	
	{'name': 'Rohit Prasanna',
	'part':['lead'],
	'start': 2014,
	'end': 2016,
	'program':'PhD',
	'study': 'materials science',
	'officer': ['pres'],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'tamil',
	'sub-sub-ethnicity':'iyengar tamil',
	'solos': ['Bure Bure', 'Chandrachooda (swaram)', 'Chaiyyan Chaiyyan', 'Swing Low (lower)'],
	},
	{'name': 'Connor Holland',
	'part':['bari'],
	'start': 2014,
	'end': 2016,
	'program':'undergrad',
	'study': 'physics',
	'officer': ['md'],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'white',
	'sub-ethnicity':'dutch/german/english',
	'solos': ['Chaiyyan Chaiyyan', 'Ey Karevan'],
	'father': 'Bradley Wo',
	},
	{'name': 'Sandip Srinivas',
	'part':['bari'],
	'start': 2014,
	'end': 2016,
	'program':'undergrad',
	'study': 'symsys',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'tamil',
	'sub-ethnicity':'iyer tamil',
	'solos': ['Hallelujah (1+2)', 'Pani Da', 'Swing Low (If you get there...)'],
	},
	{'name': 'Suraj Bulchand',
	'part':['bari'],
	'start': 2014,
	'end': 2015,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'tamil',
	'sub-sub-ethnicity':'malaysian tamil',
	'solos': ['Hallelujah (3)', "Feeling Good", 'Superstition'],
	},	
	{'name': 'Neeraj Rajasekar',
	'part':['bass', 'vp'],
	'start': 2014,
	'end': 2015,
	'program':'masters',
	'study': 'environmental science',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'tamil',
	'solos': ['Vande yahan vahan'],
	},
	{'name': 'Kyle D\'Souza',
	'part':['bass'],
	'start': 2014,
	'end': 2015,
	'program':'undergrad',
	'study': 'symsys',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'goa',
	'solos': ["Motel"],
	},
	{'name': 'Pranav Sriram',
	'part':['lead'],
	'start': 2014,
	'end': 2016,
	'program':'undergrad',
	'study': 'cs',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'?',
	'solos': ['Woh Lamhe'],
	},
	{'name': 'Andrew Han',
	'part':['bass'],
	'start': 2014,
	'end': 2014.001,
	'program':'undergrad',
	'study': 'cs',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': [],
	},
	{'name': 'Kevin Hsu',
	'part':['lead'],
	'start': 2014,
	'end': 2016,
	'program':'undergrad',
	'study': 'MechE?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': ['Woh Lamhe opening'],
	},
	{'name': 'Nikhil Goel',
	'part':['top'],
	'start': 2014,
	'end': 2016,
	'program':'undergrad',
	'study': 'symsys',
	'officer': [],
	'arranged':[],
	'training': 'hindustani',
	'ethnicity': 'south asian',
	'sub-ethnicity':'UP',
	'solos': ['Jaane Kya Chahe','Chaiyyan Chaiyyan (Jinke saare..)', "Motel (it's all right)", 'Vande tere pas', 'Woh Lamhe'],
	},
#==========================================================
#----------------------------------------------------------
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
#2015 admitees, under Onkur	
	{'name': 'Ronald Tep',
	'part':['bass'],
	'start': 2015,
	'end': 0,
	'program':'undergrad',
	'study': 'undeclared',
	'officer': [],
	'arranged':['Hosanna'],
	'training': 'none',
	'ethnicity': 'southeast asian',
	'sub-ethnicity':'cambodian',
	'solos': ["Hallelujah 2", "yahan vahan"],
	},
	{'name': 'Ben Wu',
	'part':['bass'],
	'start': 2015,
	'end': 0,
	'program':'undergrad',
	'study': 'cs',
	'officer': [],
	'arranged':[],
	'training': 'choir',
	'ethnicity': 'east asian',
	'sub-ethnicity':'chinese',
	'solos': ["Hallelujah 1"],
	},	
	{'name': 'Jaydeep Singh',
	'part':['bari'],
	'start': 2015,
	'end': 0,
	'program':'undergrad',
	'study': 'physics',
	'officer': [],
	'arranged':[],
	'training': 'choir',
	'ethnicity': 'south asian',
	'sub-ethnicity':'punjabi',
	'solos': ["chan chan (middle)"],
	},	
	{'name': 'Gautam Rao',
	'part':['bari'],
	'start': 2015,
	'end': 2015.3,
	'program':'master',
	'study': 'MS&E',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'telugu',
	'solos': ["Oh Carol Hindi", "JKC"],
	},		
	{'name': 'Suhas Suresha',
	'part':['bari'],
	'start': 2015,
	'end': 0,
	'program':'master',
	'study': 'CME',
	'officer': [],
	'arranged':[],
	'training': 'carnatic',
	'ethnicity': 'south asian',
	'sub-ethnicity':'tamil',
	'sub-sub-ethnicity':'iyer tamil',
	'solos': ['chandrachooda', 'mahabharat', 'woh lamhe 1st verse'],
	'father': 'Isaac Caswell',
	},		
	{'name': 'Bobby Pragada',
	'part':['lead'],
	'start': 2015,
	'end': 0,
	'program':'undergrad',
	'study': 'english',
	'officer': [],
	'arranged':[],
	'training': 'a cappella, sax',
	'ethnicity': 'white/south asian',
	'sub-ethnicity':'white/telugu',
	'solos': ['aashayein', 'O...Saya rap', 'humdum rap'],
	},	
	{'name': 'Nathan Dalal',
	'part':['lead'],
	'start': 2015,
	'end': 0,
	'program':'undergrad',
	'study': 'cs',
	'officer': [],
	'arranged':[],
	'training': 'choir',
	'ethnicity': 'south asian',
	'sub-ethnicity':'gujarati',
	'solos': ['woh lamhe opening', 'chan chan opening', 'Hallelujah 3', 'Oru Maalai'],
	},		
	{'name': 'Kuhan Jeyapragasan',
	'part':['top'],
	'start': 2015,
	'end': 0,
	'program':'undergrad',
	'study': 'undeclared',
	'officer': [],
	'arranged':[],
	'training': 'carnatic',
	'ethnicity': 'south asian',
	'sub-ethnicity':'tamil',
	'sub-sub-ethnicity':'sri lankan tamil',
	'solos': ['vande aalap', 'chanchan sargam', 'Mahabharat', 'Aicha French'],
	},	
#==========================================================
#----------------------------------------------------------
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
#2016 admitees, under Connor/Kuhan	
	{'name': 'Brian Morris',
	'part':['bass'],
	'start': 2016,
	'end': 0,
	'program':'undergrad',
	'study': 'undeclared',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'white',
	'sub-ethnicity':'?',
	'solos': [],
	},	
	{'name': 'Suraj Heereguppe',
	'part':['bass'],
	'start': 2016,
	'end': 0,
	'program':'masters',
	'study': 'CME',
	'officer': [],
	'arranged':[],
	'training': 'carnatic',
	'ethnicity': 'kannada?tamil?',
	'sub-ethnicity':'?',
	'solos': [],
	'father': 'Suhas Suresha',
	},	
	{'name': 'Ben Strauber',
	'part':['bari'],
	'start': 2016,
	'end': 0,
	'program':'PhD',
	'study': 'neuroscience',
	'officer': [],
	'arranged':[],
	'training': 'none?',
	'ethnicity': 'white',
	'sub-ethnicity':'?',
	'solos': [],
	},	
	{'name': 'James Thieu',
	'part':['bari'],
	'start': 2016,
	'end': 0,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none?',
	'ethnicity': 'southeast asian',
	'sub-ethnicity':'vietnamese',
	'solos': [],
	},	
	{'name': 'Siddarth Bommakanti',
	'part':['bari'],
	'start': 2016,
	'end': 0,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'none',
	'ethnicity': 'south asian',
	'sub-ethnicity':'telugu?',
	'solos': [],
	},	
	{'name': 'Tanay ?',
	'part':['lead'],
	'start': 2016,
	'end': 0,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'hindustani',
	'ethnicity': 'south asian',
	'sub-ethnicity':'?',
	'solos': [],
	},	
	{'name': 'Yash Manyani',
	'part':['top'],
	'start': 2016,
	'end': 0,
	'program':'undergrad',
	'study': '?',
	'officer': [],
	'arranged':[],
	'training': 'hindustani',
	'ethnicity': 'south asian',
	'sub-ethnicity':'?',
	'solos': [],
	},	
]

#===============================================================================
# TODO:
# 	-add international vs not
#	-how did they decide to join?  (white plaza, O-show, etc)
#	-raagfather?
# 	-make list of Song objects, each with a list of solos, and the arranger, etc.
#	-assert that ids in songs are in `raagafellas`

if __name__=="__main__":
	print "here are some pretty useless stats!  You can do better."
	print "data on admitees under Onkur is pretty patchy!"
	print 
	part_names = ['bass','bari','lead','top','vp']
	by_part = [[fella for fella in raagafellas if part in fella['part']] for part in part_names]

	sa_by_part = [[fella for fella in part if 'south asian' in fella['ethnicity']] for part in by_part]
	tamil_by_part = [[fella for fella in part if 'tamil' in fella['sub-ethnicity']] for part in by_part]
	ea_by_part = [[fella for fella in part if 'east asian' in fella['ethnicity']] for part in by_part]
	white_by_part = [[fella for fella in part if 'white' in fella['ethnicity']] for part in by_part]	
	carnatic_by_part = [[fella for fella in part if 'carnatic' in fella['training']] for part in by_part]	
	hindustani_by_part = [[fella for fella in part if 'hindustani' in fella['training']] for part in by_part]	
	cs_by_part = [[fella for fella in part if 'cs' in fella['study']] for part in by_part]
	grad_by_part = [[fella for fella in part if 'undergrad' not in fella['program']] for part in by_part]			

	sa_pct_by_part = [round(float(len(sa_by_part[i]))/len(by_part[i]), 2) for i in range(len(by_part))]
	tamil_pct_by_part = [round(float(len(tamil_by_part[i]))/len(by_part[i]), 2) for i in range(len(by_part))]
	ea_pct_by_part = [round(float(len(ea_by_part[i]))/len(by_part[i]), 2) for i in range(len(by_part))]
	white_pct_by_part = [round(float(len(white_by_part[i]))/len(by_part[i]), 2) for i in range(len(by_part))]
	carnatic_pct_by_part = [round(float(len(carnatic_by_part[i]))/len(by_part[i]), 2) for i in range(len(by_part))]
	hindustani_pct_by_part = [round(float(len(hindustani_by_part[i]))/len(by_part[i]), 2) for i in range(len(by_part))]
	cs_pct_by_part = [round(float(len(cs_by_part[i]))/len(by_part[i]), 2) for i in range(len(by_part))]
	grad_pct_by_part = [round(float(len(grad_by_part[i]))/len(by_part[i]), 2) for i in range(len(by_part))]

	print "parts:\t\t\t\t\t ", '[' + ", ".join(part_names) + ']'
	print "-"*80
	print "sa_pct_by_part:\t\t\t ", sa_pct_by_part 
	print "tamil_pct_by_part:\t\t ", tamil_pct_by_part 
	print "ea_pct_by_part:\t\t\t ", ea_pct_by_part 
	print "white_pct_by_part:\t\t ", white_pct_by_part 
	print "carnatic_pct_by_part:\t ", carnatic_pct_by_part 
	print "hindustani_pct_by_part:\t ", hindustani_pct_by_part 
	print "cs_pct_by_part:\t\t\t ", cs_pct_by_part 
	print "grad_pct_by_part:\t\t ", grad_pct_by_part

	print "fellas per part: \t\t ",  [len(part) for part in by_part] 
